---
- name: Add ansible stable repository from PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible

- name: Install pre-req
  become: true
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - ansible
      - curl
      - git
      - git-flow
    state: present
